#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

GREEN="\033[0;32m"
NC="\033[0m"

# format backend backend dotnet
echo -e "${GREEN}formatting dotnet code${NC}"
dotnet format clean-lean-arch-dotnet-api-template.sln --verbosity detailed
